config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"

  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_one_attached :photo
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail, message: "already added" }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = Cocktail.find(@dose.cocktail_id)
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<%= render "shared/banner"%>

<br>
<div class="container">
  <div class="cards">
    <% @cocktails.each do |cocktail| %>
      <div class="card-product">
      <% if cocktail.photo.attached? %>
          <%= cl_image_tag cocktail.photo.key, crop: :fill, class: 'img-card' %>
      <% end %>
      <div class="card-product-infos">
        <h2><%= link_to  "#{cocktail.name}", cocktail_path(cocktail) %></h2>
        <% cocktail.doses.each do |dose| %>
          <p><%=dose.ingredient.name%> : <%=dose.description%> </p>
        <% end %>
      </div>
      <br>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=749&q=80);">
  <div class="container">
    <h1>Cocotails</h1>
  </div>
</div>
<br>
<div class="container">
  <h1>Design you own cocktail</h1>
  <br>
  <%= render "form", cocktail: @cocktail %>
</div>
<br>
<br>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.photo.key, crop: :fill %>')">
  <div class="container">
    <h1><%= @cocktail.name%></h1>
  </div>
</div>

<div class="container">
  <div class="ingredients">
    <h2>List of ingredients</h2>
    <% @cocktail.doses.each do |dose| %>
      <li><%= dose.ingredient.name %> - <%= dose.description %>
        <%= link_to "Delete", dose_path(dose), method: :delete %>
      </li>
    <% end %>
  </div>
  <br>
  <p><%= link_to "Add an ingredient", new_cocktail_dose_path(@cocktail), {:style=>'text-align: center;'}  %></p>
  <br>
  <%= link_to "Back to the list of cocktails", root_path  %>
</div>

app/views/doses/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.photo.key, crop: :fill %>')">
  <div class="container">
    <h1><%= @cocktail.name%></h1>
  </div>
</div>
<br>
<div class="container">
  <h1>Add an ingredient</h1>
  <br>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient %>
    <br>
    <%= f.input :description %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>

    <%= yield %>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1470337458703-46ad1756a187?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=749&q=80);">
  <div class="container">
    <h1>Cocotails</h1>
    <p>Best drinks in town</p>
    <%= link_to "Add your recipe", new_cocktail_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div>Enjoy your drink!</div>
  <div class="footer-copyright">delphinehab</div>
</div>